
return {
["stumpyhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.8,
      flashsize          = 18,
      ttl                = 10,
      color              = [[0.8,0.4,0.4]],
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 1 0.01  0.9 0.6 0.6 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 65,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 4,
        particlelife       = 16,
        particlelifespread = 3,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 2, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[spark]],
      },
    },
},
["llt1hit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.8,
      flashsize          = 36,
      ttl                = 14,
      color              = [[1,0.5,0.5]],
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 1 0.01   1 0.7 0.7 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 65,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 5,
        particlelife       = 16,
        particlelifespread = 3,
        particlesize       = 2.25,
        particlesizespread = 1.25,
        particlespeed      = 2.5,
        particlespeedspread = 2, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[spark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[1,0.5,0.5]],
                expansionspeed     = 1,
                ttl                = 16,
            },
        },
},
["commanderhit"] = {
  usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 1.5,
      flashalpha         = 0.8,
      flashsize          = 28,
      ttl                = 14,
      color              = [[0.35,1,0.45]],
    },
   spark = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
	  water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 1 0.01   0.45 0.9 0.6 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 65,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.6, 0]],
        numparticles       = 6,
        particlelife       = 18,
        particlelifespread = 4,
        particlesize       = 2.5,
        particlesizespread = 1.5,
        particlespeed      = 2.5,
        particlespeedspread = 2, --4
        pos                = [[0, 1, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[spark]],
      },
    },
	sphere = {
            air                = true,
            class              = [[CSpherePartSpawner]],
            count              = 1,
            ground             = true,
            water              = true,
            properties = {
                alpha              = 0.5,
                alwaysvisible      = true,
                color              = [[0.35,1,0.45]],
                expansionspeed     = 1,
                ttl                = 16,
            },
        },
},
}